# Copyright (c) 2022 - 2023, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

name: Build and push Docker image
on:
  workflow_call:
    # outputs:
    #   artifacts-sha256:
    #     description: The hash of the Docker image
    #     value: ${{ jobs.build-docker.outputs.image-digest }}
permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/tromai/macaron
  DIST_PATH: download/${{ inputs.artifact_name }}/dist

jobs:
  build-docker:
    runs-on: ubuntu-latest
    # outputs:
    #   image-digest: ${{ steps.build_docker.outputs.digest }}

    steps:
    - name: Check out repository
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      with:
        fetch-depth: 0

    - name: Download artifact
      uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 # v3.0.1
      with:
        path: download

    - name: Check downloaded artifact
      run: ls -R
      working-directory: ./

    - name: Log in to GitHub Container Registry
      run: docker login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Macaron final image
      run: |
        WHEEL_PATH=$(find ./download/ -depth -type f -name 'macaron-*.whl' | head -n 1)
        docker build -t ${{ env.IMAGE_NAME }}:staging --build-arg WHEEL_PATH="$WHEEL_PATH" -f docker/Dockerfile.final .
        docker push ${{ env.IMAGE_NAME }}:staging
