# Copyright (c) 2022 - 2023, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

on:
  push:
    branches:
    - tromai/add-docker-images

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    permissions:
      contents: read

  build_docker_but_not_push:
    needs: [build]
    uses: ./.github/workflows/_build_docker.yaml
    permissions:
      contents: read

  build_docker_and_push:
    needs: [build]
    uses: ./.github/workflows/_build_docker.yaml
    with:
      release-tag: experimental
    permissions:
      contents: read
      packages: write
